# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{blather}
  s.version = "0.4.12"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeff Smick"]
  s.date = %q{2010-08-09}
  s.description = %q{An XMPP DSL for Ruby written on top of EventMachine and Nokogiri}
  s.email = %q{sprsquish@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    "examples/echo.rb",
     "examples/execute.rb",
     "examples/ping_pong.rb",
     "examples/print_hierarchy.rb",
     "examples/rosterprint.rb",
     "examples/stream_only.rb",
     "examples/xmpp4r/echo.rb",
     "lib/blather.rb",
     "lib/blather/client.rb",
     "lib/blather/client/client.rb",
     "lib/blather/client/dsl.rb",
     "lib/blather/client/dsl/pubsub.rb",
     "lib/blather/core_ext/active_support.rb",
     "lib/blather/core_ext/active_support/inheritable_attributes.rb",
     "lib/blather/core_ext/nokogiri.rb",
     "lib/blather/errors.rb",
     "lib/blather/errors/sasl_error.rb",
     "lib/blather/errors/stanza_error.rb",
     "lib/blather/errors/stream_error.rb",
     "lib/blather/jid.rb",
     "lib/blather/roster.rb",
     "lib/blather/roster_item.rb",
     "lib/blather/stanza.rb",
     "lib/blather/stanza/disco.rb",
     "lib/blather/stanza/disco/disco_info.rb",
     "lib/blather/stanza/disco/disco_items.rb",
     "lib/blather/stanza/iq.rb",
     "lib/blather/stanza/iq/command.rb",
     "lib/blather/stanza/iq/query.rb",
     "lib/blather/stanza/iq/roster.rb",
     "lib/blather/stanza/message.rb",
     "lib/blather/stanza/presence.rb",
     "lib/blather/stanza/presence/status.rb",
     "lib/blather/stanza/presence/subscription.rb",
     "lib/blather/stanza/pubsub.rb",
     "lib/blather/stanza/pubsub/affiliations.rb",
     "lib/blather/stanza/pubsub/create.rb",
     "lib/blather/stanza/pubsub/errors.rb",
     "lib/blather/stanza/pubsub/event.rb",
     "lib/blather/stanza/pubsub/items.rb",
     "lib/blather/stanza/pubsub/publish.rb",
     "lib/blather/stanza/pubsub/retract.rb",
     "lib/blather/stanza/pubsub/subscribe.rb",
     "lib/blather/stanza/pubsub/subscription.rb",
     "lib/blather/stanza/pubsub/subscriptions.rb",
     "lib/blather/stanza/pubsub/unsubscribe.rb",
     "lib/blather/stanza/pubsub_owner.rb",
     "lib/blather/stanza/pubsub_owner/delete.rb",
     "lib/blather/stanza/pubsub_owner/purge.rb",
     "lib/blather/stanza/x.rb",
     "lib/blather/stream.rb",
     "lib/blather/stream/client.rb",
     "lib/blather/stream/component.rb",
     "lib/blather/stream/features.rb",
     "lib/blather/stream/features/resource.rb",
     "lib/blather/stream/features/sasl.rb",
     "lib/blather/stream/features/session.rb",
     "lib/blather/stream/features/tls.rb",
     "lib/blather/stream/parser.rb",
     "lib/blather/xmpp_node.rb"
  ]
  s.homepage = %q{http://github.com/sprsquish/blather}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{squishtech}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simpler XMPP built for speed}
  s.test_files = [
    "spec/blather/client/client_spec.rb",
     "spec/blather/client/dsl/pubsub_spec.rb",
     "spec/blather/client/dsl_spec.rb",
     "spec/blather/core_ext/nokogiri_spec.rb",
     "spec/blather/errors/sasl_error_spec.rb",
     "spec/blather/errors/stanza_error_spec.rb",
     "spec/blather/errors/stream_error_spec.rb",
     "spec/blather/errors_spec.rb",
     "spec/blather/jid_spec.rb",
     "spec/blather/roster_item_spec.rb",
     "spec/blather/roster_spec.rb",
     "spec/blather/stanza/discos/disco_info_spec.rb",
     "spec/blather/stanza/discos/disco_items_spec.rb",
     "spec/blather/stanza/iq/command_spec.rb",
     "spec/blather/stanza/iq/query_spec.rb",
     "spec/blather/stanza/iq/roster_spec.rb",
     "spec/blather/stanza/iq_spec.rb",
     "spec/blather/stanza/message_spec.rb",
     "spec/blather/stanza/presence/status_spec.rb",
     "spec/blather/stanza/presence/subscription_spec.rb",
     "spec/blather/stanza/presence_spec.rb",
     "spec/blather/stanza/pubsub/affiliations_spec.rb",
     "spec/blather/stanza/pubsub/create_spec.rb",
     "spec/blather/stanza/pubsub/event_spec.rb",
     "spec/blather/stanza/pubsub/items_spec.rb",
     "spec/blather/stanza/pubsub/publish_spec.rb",
     "spec/blather/stanza/pubsub/retract_spec.rb",
     "spec/blather/stanza/pubsub/subscribe_spec.rb",
     "spec/blather/stanza/pubsub/subscription_spec.rb",
     "spec/blather/stanza/pubsub/subscriptions_spec.rb",
     "spec/blather/stanza/pubsub/unsubscribe_spec.rb",
     "spec/blather/stanza/pubsub_owner/delete_spec.rb",
     "spec/blather/stanza/pubsub_owner/purge_spec.rb",
     "spec/blather/stanza/pubsub_owner_spec.rb",
     "spec/blather/stanza/pubsub_spec.rb",
     "spec/blather/stanza/x_spec.rb",
     "spec/blather/stanza_spec.rb",
     "spec/blather/stream/client_spec.rb",
     "spec/blather/stream/component_spec.rb",
     "spec/blather/stream/parser_spec.rb",
     "spec/blather/xmpp_node_spec.rb",
     "spec/fixtures/pubsub.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, [">= 0.12.6"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4.0"])
    else
      s.add_dependency(%q<eventmachine>, [">= 0.12.6"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.0"])
    end
  else
    s.add_dependency(%q<eventmachine>, [">= 0.12.6"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.0"])
  end
end

